### ISSUE TITLE
Just broke your APP with a cranlogs API change

### ISSUE THREAD

**Issue by gaborcsardi** [dgrtwo/cranview#2]
Sorry about it.

**Comment by dgrtwo** [comment]
No problem, thanks for letting me know

**Comment by gaborcsardi** [comment]
Yeah, so you can query multiple packages now, and it was just easier to always return a list. If you handle a list, and plot each element separately, then you can plot multiple packages. 

Also, dates are dates now, so no need to convert them.

**Comment by dgrtwo** [comment]
That's great about multiple packages; I'll change the app to allow entering multiple comma-separated package names so they can be compared.

But for plotting multiple packages, why not combine the lists into a data frame with an additional `package` column to distinguish them (i.e. ldply them)? Then it's much easier to plot them together in ggplot2 with

```
ggplot(ret$downloads, aes(day, downloads, color = package)) + geom_line()
```

Or in traditional R plotting with:

```
with(ret$downloads, plot(day, downloads, package, type = "l")
```

Giving them as a list requires using a for loop to plot.

**Comment by gaborcsardi** [comment]
The output is a data frame, look at https://github.com/metacran/cranlogs.

**Comment by dgrtwo** [comment]
Ah, I understand now: I was using the old version of the `cranlogs` package, which when combined with the new API returned a list. This looks great and I'll adapt the app to handle multiple packages accordingly.
